server:
  port: 3000
  servlet:
    context-path: /xypt
spring:
  application:
    name: campus-gateway-provider
  cloud:
    nacos:
      server-addr: 106.52.154.238:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: campus-service-common
          uri: lb://campus-service-common
          predicates:
            - Path=/xypt/api/common/**
        - id: campus-backend-service-provider
          uri: lb://campus-backend-service-provider
          predicates:
            - Path=/xypt/api/backend/**
        - id: campus-service-provider
          uri: lb://campus-service-provider
          predicates:
            - Path=/xypt/api/client/**
